# Hypothesis Testing: Weekly Operating Cost

We want to check if the weekly cost of restaurants is higher than the model predicts.

## Step 1: State the Hypotheses
- **Null Hypothesis (H0):** The average weekly cost = Rs. 4000 (model is correct).
- **Alternative Hypothesis (H1):** The average weekly cost > Rs. 4000 (cost is higher than model).

## Step 2: Calculate Theoretical Cost
The cost model is:
\[ W = 1000 + 5X \]
For X = 600 units:
\[ W = 1000 + 5(600) = 4000 \]
So, the theoretical mean = Rs. 4000.

In [1]:
import math

# Given values
sample_mean = 3050  # observed mean
mu = 1000 + 5*600   # theoretical mean
sigma = 5*25        # standard deviation of weekly cost
n = 25              # sample size

mu

4000

## Step 3: Compute the Test Statistic
Formula:
\[ t = \frac{\bar{x} - \mu}{\sigma / \sqrt{n}} \]

- \(\bar{x}\) = 3050
- \(\mu\) = 4000
- \(\sigma\) = 125
- \(n\) = 25

In [2]:
t_stat = (sample_mean - mu) / (sigma / math.sqrt(n))
t_stat

-38.0

## Step 4: Find the Critical Value
For alpha = 0.05 and a **right-tailed test**, the critical value from Z-table is:
\[ Z_{0.05} = 1.645 \]

In [3]:
critical_value = 1.645
critical_value

1.645

## Step 5: Make a Decision
- If t > critical value-> Reject H0 (cost is higher).
- If t ≤ critical value -> Do not reject H0 (cost is not higher).

In [5]:
if t_stat > critical_value:
    result = "Reject H0 -> Costs are higher than model predicts."
else:
    result = "Do not reject H0 -> Not enough proof that costs are higher."
result

'Do not reject H0 -> Not enough proof that costs are higher.'

## Step 6: Conclusion

* The model says the average weekly cost should be **₹4000**.
* Our sample of 25 restaurants has an average of **₹3050**, which is **lower**, not higher.
* Test statistic = **-38.0** and the right-tail critical value at 5% is **1.645**.
* Because **-38.0 < 1.645**, we **do not reject** the null hypothesis.
There is **no evidence** that weekly costs are higher than the model. In fact, this sample suggests costs are **much lower** than ₹4000. If the claim is “costs are higher,” this data **does not support** that claim.
